default: &default
  adapter: postgresql
  encoding: unicode
  host: db               # docker-composeのサービス名
  username: user         # POSTGRES_USERと合わせる
  password: password     # POSTGRES_PASSWORDと合わせる
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mini_blog_development

test:
  <<: *default
  database: mini_blog_test
  username: postgres
  password: password
  host: db

production:
  <<: *default
  database: mini_blog_production
  username: mini_blog
  password: <%= ENV['MINI_BLOG_DATABASE_PASSWORD'] %>
