default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mini_blog_development

test:
  <<: *default
  database: mini_blog_test

production:
  <<: *default
  database: mini_blog_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] || "db" %>
